// Package nginx puts every TLS protocol the panel serves behind a single
// public port, so that from the outside the server looks like an ordinary
// website: one open port, a real site behind it, and the protocols told apart
// by the SNI the client sends.
//
// The split across two files is not cosmetic. A distro's nginx.conf includes
// conf.d/*.conf from inside http {}, so the stream {} block — the part that
// actually multiplexes 443 — cannot live there. It goes into its own directory
// that the panel wires into nginx.conf with a marked include, the same way the
// ndppd package owns its section of ndppd.conf.
package nginx

import (
	"errors"
	"fmt"
	"sort"
	"strings"
)

// Mode is how much of the server nginx is in front of.
type Mode string

const (
	// ModeOff leaves the server alone: no config is generated and every
	// inbound keeps its own port.
	ModeOff Mode = "off"
	// ModeShared puts 443 behind nginx but leaves the other ports open, so a
	// client that cannot reach 443 still has a way in.
	ModeShared Mode = "shared"
	// ModeOnly443 is ModeShared plus a firewall that closes everything else.
	ModeOnly443 Mode = "only443"
)

// Valid reports whether m is one of the three known modes.
func (m Mode) Valid() bool {
	return m == ModeOff || m == ModeShared || m == ModeOnly443
}

// header marks the generated files as ours. Apply refuses to overwrite a file
// that does not carry it, so a config someone wrote by hand is never lost.
const header = "# Generated by 3AX-UI. Do not edit: this file is rewritten whenever the\n" +
	"# nginx settings are applied. Hand-written config belongs in another file.\n"

// Route is one SNI-matched destination behind the public port. A Reality
// inbound brings several server names, hence the slice.
type Route struct {
	Name     string   // inbound remark, written as a comment
	SNIs     []string // server names this route answers to
	Upstream string   // host:port to hand the untouched stream to
	Fallback bool     // takes connections whose SNI matches nothing

	// Relay is a loopback address nginx listens on to take the PROXY protocol
	// header off again before handing the stream to Upstream.
	//
	// It exists because an inbound that keeps its own port has to serve two
	// kinds of client at once: people connecting straight to that port, who
	// send nothing extra, and people arriving through 443, whom the stream
	// block prefixes with a PROXY header. One listener cannot accept both —
	// a receiver told to expect the header must reject a connection without
	// it — so the header is stripped on the way in instead. The cost is that
	// clients arriving via 443 reach the inbound as 127.0.0.1.
	//
	// Empty for an inbound that gave up its own port: nothing reaches it
	// except through nginx, so it keeps the header and with it the real
	// client address.
	Relay string
}

// target is where the map sends this route: through the relay when there is
// one, straight to the inbound otherwise.
func (r Route) target() string {
	if r.Relay != "" {
		return r.Relay
	}
	return r.Upstream
}

// Proxy is one HTTP service published under the site's domain.
type Proxy struct {
	Name   string
	Paths  []string // URL prefixes, each ending in "/"
	Target string   // host:port
	TLS    bool     // the service speaks HTTPS on that port
}

// Site is the HTTPS server that terminates TLS for our own domain: the stub
// page, and — depending on the mode — the panel and the subscriptions.
type Site struct {
	Domain   string
	CertFile string
	KeyFile  string
	Listen   string // where the stream block hands our domain over
	Root     string // document root of the stub page
	Panel    *Proxy
	Sub      *Proxy
}

// Config is everything the generator needs. It is filled from the panel's
// settings and inbounds by web/service/nginx_service.go.
type Config struct {
	Mode   Mode
	Port   int // public port, 443
	Routes []Route
	Site   *Site
}

// Validate reports the mistakes that would either break nginx or, worse, load
// cleanly and silently route the wrong protocol to the wrong place.
func (c Config) Validate() error {
	if !c.Mode.Valid() {
		return fmt.Errorf("unknown nginx mode %q", c.Mode)
	}
	if c.Mode == ModeOff {
		return nil
	}
	if c.Port <= 0 || c.Port > 65535 {
		return fmt.Errorf("public port %d is out of range", c.Port)
	}
	if len(c.Routes) == 0 && c.Site == nil {
		return errors.New("nothing to serve on the public port")
	}

	// Two protocols behind the same server name is the one mistake nginx
	// cannot catch: the map keeps the last entry and the other protocol goes
	// quietly dark.
	seen := map[string]string{}
	claim := func(name, owner string) error {
		key := strings.ToLower(strings.TrimSpace(name))
		if key == "" {
			return fmt.Errorf("%s has an empty server name", owner)
		}
		if prev, dup := seen[key]; dup {
			return fmt.Errorf("server name %q is claimed by both %s and %s", key, prev, owner)
		}
		seen[key] = owner
		return nil
	}

	fallbacks := 0
	relays := map[string]string{}
	for _, r := range c.Routes {
		if r.Upstream == "" {
			return fmt.Errorf("route %q has no upstream", r.Name)
		}
		if r.Relay != "" {
			if r.Relay == r.Upstream {
				return fmt.Errorf("route %q relays to itself", r.Name)
			}
			if prev, dup := relays[r.Relay]; dup {
				return fmt.Errorf("routes %q and %q share the relay address %s", prev, r.Name, r.Relay)
			}
			relays[r.Relay] = r.Name
		}
		if r.Fallback {
			fallbacks++
		}
		if len(r.SNIs) == 0 && !r.Fallback {
			return fmt.Errorf("route %q matches no server name and is not the fallback", r.Name)
		}
		for _, sni := range r.SNIs {
			if err := claim(sni, r.Name); err != nil {
				return err
			}
		}
	}
	if fallbacks > 1 {
		return errors.New("more than one route claims the fallback")
	}

	if c.Site != nil {
		if c.Site.Domain == "" {
			return errors.New("the site has no domain")
		}
		if c.Site.CertFile == "" || c.Site.KeyFile == "" {
			return fmt.Errorf("no certificate for %s", c.Site.Domain)
		}
		if c.Site.Listen == "" {
			return errors.New("the site has no listen address")
		}
		// The site terminates TLS on a loopback port and so does every relay.
		// Two servers on one address is the mistake `nginx -t` cannot catch,
		// because it binds nothing: the config tests clean and then nginx will
		// not start.
		if owner, dup := relays[c.Site.Listen]; dup {
			return fmt.Errorf("the site and route %q both listen on %s", owner, c.Site.Listen)
		}
		if err := claim(c.Site.Domain, "the site"); err != nil {
			return err
		}
		for _, p := range []*Proxy{c.Site.Panel, c.Site.Sub} {
			if p == nil {
				continue
			}
			if p.Target == "" {
				return fmt.Errorf("%s has no target", p.Name)
			}
			if len(p.Paths) == 0 {
				return fmt.Errorf("%s has no path", p.Name)
			}
		}
	}
	return nil
}

// fallbackUpstream is where a connection goes when its SNI matches nothing.
//
// Reality gets it when it is there, and that is deliberate: Reality answers an
// unknown server name by handing the connection to the real site it borrows
// its identity from, which is a far better answer to a prober than our own
// certificate for a domain it never asked for.
func (c Config) fallbackUpstream() string {
	for _, r := range c.Routes {
		if r.Fallback {
			return r.target()
		}
	}
	if c.Site != nil {
		return c.Site.Listen
	}
	if len(c.Routes) > 0 {
		return c.Routes[0].target()
	}
	return ""
}

// StreamConf renders the stream block: read the SNI, hand the bytes over
// untouched. Nothing here terminates TLS.
func (c Config) StreamConf() (string, error) {
	if err := c.Validate(); err != nil {
		return "", err
	}
	if c.Mode == ModeOff {
		return "", nil
	}

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n")

	b.WriteString("map $ssl_preread_server_name $threeax_upstream {\n")
	// hostnames lets a route be written as ".example.com" and cover the
	// subdomains too; without it the map would only match exactly.
	b.WriteString("    hostnames;\n\n")
	if c.Site != nil {
		fmt.Fprintf(&b, "    # panel domain\n    %s %s;\n\n", c.Site.Domain, c.Site.Listen)
	}
	for _, r := range c.Routes {
		if len(r.SNIs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "    # %s\n", r.Name)
		for _, sni := range sortedLower(r.SNIs) {
			fmt.Fprintf(&b, "    %s %s;\n", sni, r.target())
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "    default %s;\n", c.fallbackUpstream())
	b.WriteString("}\n\n")

	b.WriteString("server {\n")
	fmt.Fprintf(&b, "    listen %d;\n", c.Port)
	fmt.Fprintf(&b, "    listen [::]:%d;\n\n", c.Port)
	b.WriteString("    ssl_preread on;\n")
	fmt.Fprintf(&b, "    proxy_pass $threeax_upstream;\n")
	// Without this every client would reach Xray as 127.0.0.1 and the per
	// client IP limit, the online counter and the logs would all be fiction.
	// The other end of each upstream has to be told to expect it.
	b.WriteString("    proxy_protocol on;\n")
	b.WriteString("    proxy_timeout 300s;\n")
	b.WriteString("    proxy_connect_timeout 5s;\n")
	b.WriteString("}\n")

	// One relay per inbound that kept its own port: it accepts the PROXY
	// header from the block above and passes a plain stream on, so the same
	// listener can also serve people connecting to that port directly.
	for _, r := range c.Routes {
		if r.Relay == "" {
			continue
		}
		fmt.Fprintf(&b, "\n# %s — keeps its own port, so the PROXY header is taken off here\n", r.Name)
		b.WriteString("server {\n")
		fmt.Fprintf(&b, "    listen %s proxy_protocol;\n", r.Relay)
		fmt.Fprintf(&b, "    proxy_pass %s;\n", r.Upstream)
		b.WriteString("    proxy_timeout 300s;\n")
		b.WriteString("    proxy_connect_timeout 5s;\n")
		b.WriteString("}\n")
	}
	return b.String(), nil
}

// HTTPConf renders the server block for our own domain. Empty when there is no
// site to serve, which is a valid setup: 443 can be pure SNI passthrough.
func (c Config) HTTPConf() (string, error) {
	if err := c.Validate(); err != nil {
		return "", err
	}
	if c.Mode == ModeOff || c.Site == nil {
		return "", nil
	}
	s := c.Site

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n")

	if s.Panel != nil || s.Sub != nil {
		// Own name so that a map by the usual name in another conf.d file
		// does not collide with ours.
		b.WriteString("map $http_upgrade $threeax_connection_upgrade {\n")
		b.WriteString("    default upgrade;\n")
		b.WriteString("    ''      close;\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("server {\n")
	// proxy_protocol here is the other half of the stream block's
	// proxy_protocol on — the two are set and cleared together.
	fmt.Fprintf(&b, "    listen %s ssl proxy_protocol;\n", s.Listen)
	fmt.Fprintf(&b, "    server_name %s;\n\n", s.Domain)

	b.WriteString("    set_real_ip_from 127.0.0.1;\n")
	b.WriteString("    real_ip_header proxy_protocol;\n\n")

	fmt.Fprintf(&b, "    ssl_certificate     %s;\n", s.CertFile)
	fmt.Fprintf(&b, "    ssl_certificate_key %s;\n", s.KeyFile)
	b.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
	b.WriteString("    ssl_session_cache shared:threeax:10m;\n")
	b.WriteString("    ssl_session_timeout 1d;\n")
	b.WriteString("    ssl_prefer_server_ciphers off;\n\n")

	b.WriteString("    access_log off;\n")
	b.WriteString("    server_tokens off;\n\n")

	for _, p := range []*Proxy{s.Panel, s.Sub} {
		if p == nil {
			continue
		}
		writeProxy(&b, p)
	}

	fmt.Fprintf(&b, "    root %s;\n", s.Root)
	b.WriteString("    index index.html;\n\n")
	b.WriteString("    location / {\n")
	b.WriteString("        try_files $uri $uri/ /index.html;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String(), nil
}

// writeProxy emits one location per path of a proxied service. The panel needs
// the websocket upgrade for its live traffic view and a long read timeout to
// keep it open.
func writeProxy(b *strings.Builder, p *Proxy) {
	scheme := "http"
	if p.TLS {
		scheme = "https"
	}
	for _, path := range p.Paths {
		fmt.Fprintf(b, "    # %s\n", p.Name)
		fmt.Fprintf(b, "    location %s {\n", path)
		fmt.Fprintf(b, "        proxy_pass %s://%s;\n", scheme, p.Target)
		if p.TLS {
			// The panel's certificate is whatever the operator gave it and
			// the hop is over the loopback, so there is nothing to verify.
			b.WriteString("        proxy_ssl_verify off;\n")
		}
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Host $host;\n")
		b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
		b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection $threeax_connection_upgrade;\n")
		b.WriteString("        proxy_read_timeout 3600s;\n")
		b.WriteString("        proxy_buffering off;\n")
		b.WriteString("    }\n\n")
	}
}

// sortedLower normalises and orders server names so that the same inbound
// always renders the same bytes — otherwise every save would look like a
// config change and reload nginx for nothing.
func sortedLower(names []string) []string {
	out := make([]string, 0, len(names))
	for _, n := range names {
		if n = strings.ToLower(strings.TrimSpace(n)); n != "" {
			out = append(out, n)
		}
	}
	sort.Strings(out)
	return out
}
